### ISSUE TITLE
F3 Emote

### ISSUE THREAD

**Issue by AceGrid** [StockholmCityRP/scrp_bugreports#6]
**_Arbetar emote : "MEKANIKER : REPARERA UNDER FORDON_"**

Denna emote går att använda för att komma in på ställen man inte egentligen ska vara dock behöver vi den till Mekanikern för ett bättre rp som t.ex. Besiktning när vi kollar under bilen och liknande. Man använder emoten sen närman trycker på "X" så kan man komma ut/in på stället.

_Mvh Enes Ajdarpasic Mekaniker Chef_

**Comment by ElPumpo** [comment]
Fixat
